require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"
    - "lib/tasks/**/*"
    - "bin/*"
    - "config/**/*"
    - Rakefile
    - Gemfile
    - "spec/**/*"
    - "vendor/**/*"


Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Style/Lambda:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
