require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PostsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # adjust the attributes here as well.
  let(:user) { create(:user) }
  let!(:user_post) { create(:post, user_id: user.id) }

  context 'when user is logged in' do

    before do
      sign_in(user)
    end

    describe "GET #index" do
      it 'shows the timeline index page' do
          get :index
          expect(response).to have_http_status(:success)
      end
    end

    describe "GET #show" do
      it 'shows the post page' do
          get :show, params: { id: user_post.id }
          expect(response).to have_http_status(:success)
      end
    end

    describe 'POST #create' do

      describe 'when new post info is valid' do
        it 'creates the new post' do
          expect{post :create, params: { post: { content: 'This is a new post!'} }}.to change{Post.count}.by(1)
          expect(Post.first.content).to eq 'This is a new post!'
          expect(response).to redirect_to(root_url)
        end
      end

      describe 'when new post does not have any content' do
        it 'does NOT create a new post' do
          expect{post :create, params: { post: { content: ''} }}.to change{Post.count}.by(0)
        end
      end

    end

    describe 'GET #edit' do

      it 'shows the edit post page' do
          get :edit, params: { id: user_post.id }
          expect(response).to have_http_status(:success)
      end

    end

    describe 'PATCH #update' do

      describe 'when edit post info is valid' do
        it 'updates the post' do
          patch :update, params: { id: user_post.id, post: { content: 'Editing my first post!'} }
          expect(user.posts.first.content).to eq 'Editing my first post!'
          expect(response).to redirect_to(user.posts.first)
        end
      end

      describe 'when edited post does not have any content' do
        it 'does NOT edit the post' do
          patch :update, params: { id: user_post.id, post: { content: ''} }
          expect(user.posts.first.content).to_not eq ''
        end
      end

    end

    describe 'DELETE #destroy' do
      it 'deletes the post' do
        expect { delete :destroy, params: { id: user_post.id } }.to change{Post.count}.by(-1)
        expect(response).to redirect_to(root_url)
      end
    end
  end

  context 'when user is not logged in' do

    describe 'GET #index' do
      it 'redirects to login page' do
        get :index
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe "GET #show" do
      it 'redirects to login page' do
          get :show, params: { id: user_post.id }
          expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe 'POST #create' do
      it 'does not create post and redirects to login' do
          expect{post :create, params: { post: { content: 'I am trying to make a post!'} }}.to change{Post.count}.by(0)
          expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe 'GET #edit' do
      it 'redirects to login page' do
          get :edit, params: { id: user_post.id }
          expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe 'PATCH #update' do
      it 'does not edit the post and redirects to login' do
        patch :update, params: { id: user_post.id, post: { content: 'Editing my first post!'} }
        expect(user.posts.first.content).to_not eq 'Editing my first post!'
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe 'DELETE #destroy' do
      it 'does NOT delete the post and redirects to login' do
        expect { delete :destroy, params: { id: user_post.id } }.to change{Post.count}.by(0)
        expect(response).to redirect_to(new_user_session_path)
      end
    end

  end

end
