require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RequestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Request. As you add validations to Request, be sure to
  # adjust the attributes here as well.
  let(:user) { create(:user) }
  let(:other_user) { create(:random_user) }
  let(:third_user) { create(:random_user) }

  context 'when user is logged in' do

    before do
      sign_in(user)
    end

    describe "GET #index" do
      it 'shows all friend requests page' do
          get :index
          expect(response).to have_http_status(:success)
      end
    end


    describe 'POST #create' do
        it 'clicking on "Add Friend" creates a new pending request' do
          expect { post :create, params: { request: { requester_id: user.id, requestee_id: other_user.id, accepted: 0 } }}.to change{Request.count}.by(1)
          expect(user.requestees).to include(other_user)
          expect(response).to redirect_to(root_url)
        end
    end


    describe 'PATCH #update' do
      it 'updates after requestee accepts the request and redirects to the requester\'s profile' do
          create(:request, requester_id: third_user.id, requestee_id: user.id)
          expect { patch :update, params: { id: user.received_requests.where('requester_id = ?', third_user.id).first.id,
                                   request: { requester_id: third_user.id, requestee_id: user.id } } }.to change{user.friends.count}.by(1)
          expect(user.friends).to include(third_user)
          expect(response).to redirect_to(third_user.profile)
      end
    end

  end

  context 'when user is NOT logged in' do

    describe 'GET #index' do
      it 'redirects to login page' do
        get :index
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe 'POST #create' do
      it 'a new pending request is not created' do
        expect { post :create, params: { request: { requester_id: user.id, requestee_id: other_user.id, accepted: 0 } }}.to change{Request.count}.by(0)
        expect(user.requestees).to_not include(other_user)
        expect(response).to redirect_to(new_user_session_path)
      end
    end


    describe 'PATCH #update' do
      it 'A friend request cannot be accepted' do
        create(:request, requester_id: third_user.id, requestee_id: user.id)

        expect { patch :update, params: { id: user.received_requests.where('requester_id = ?', third_user.id).first.id,
                                 request: { requester_id: third_user.id, requestee_id: user.id } } }.to change{user.friends.count}.by(0)
        expect(user.friends).to_not include(third_user)
        expect(response).to redirect_to(new_user_session_path)
      end
    end

  end

end
